
// Objective-C API for talking to the following Go packages
//
//	github.com/Dione-Software/dione-go/dione-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Dione_mobile_FRAMEWORK_H__
#define __Dione_mobile_FRAMEWORK_H__

#include "Dione_mobile.objc.h"
#include "Universe.objc.h"

#endif
