// Objective-C API for talking to github.com/Dione-Software/dione-go/dione-mobile Go package.
//   gobind -lang=objc github.com/Dione-Software/dione-go/dione-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Dione_mobile_H__
#define __Dione_mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Dione_mobileDioneMobileHost;
@class Dione_mobileDioneMobileTunnel;
@protocol Dione_mobileDioneMobileInterface;
@class Dione_mobileDioneMobileInterface;

@protocol Dione_mobileDioneMobileInterface <NSObject>
- (NSString* _Nonnull)closest:(NSString* _Nullable)key;
- (id<Dione_mobileDioneMobileInterface> _Nullable)connect:(NSString* _Nullable)peer;
- (NSData* _Nullable)getKad:(NSString* _Nullable)key;
- (void)putKad:(NSString* _Nullable)key value:(NSData* _Nullable)value;
@end

@interface Dione_mobileDioneMobileHost : NSObject <goSeqRefInterface, Dione_mobileDioneMobileInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)closest:(NSString* _Nullable)key;
- (id<Dione_mobileDioneMobileInterface> _Nullable)connect:(NSString* _Nullable)p0;
- (NSData* _Nullable)getKad:(NSString* _Nullable)key;
- (NSString* _Nonnull)peers;
- (void)putKad:(NSString* _Nullable)key value:(NSData* _Nullable)value;
@end

@interface Dione_mobileDioneMobileTunnel : NSObject <goSeqRefInterface, Dione_mobileDioneMobileInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSString* _Nonnull)closest:(NSString* _Nullable)key;
- (id<Dione_mobileDioneMobileInterface> _Nullable)connect:(NSString* _Nullable)p0;
- (NSData* _Nullable)getKad:(NSString* _Nullable)key;
- (void)putKad:(NSString* _Nullable)key value:(NSData* _Nullable)value;
@end

FOUNDATION_EXPORT NSString* _Nonnull Dione_mobileGreetings(NSString* _Nullable name);

FOUNDATION_EXPORT Dione_mobileDioneMobileHost* _Nullable Dione_mobileNew(void);

@class Dione_mobileDioneMobileInterface;

@interface Dione_mobileDioneMobileInterface : NSObject <goSeqRefInterface, Dione_mobileDioneMobileInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (NSString* _Nonnull)closest:(NSString* _Nullable)key;
- (id<Dione_mobileDioneMobileInterface> _Nullable)connect:(NSString* _Nullable)peer;
- (NSData* _Nullable)getKad:(NSString* _Nullable)key;
- (void)putKad:(NSString* _Nullable)key value:(NSData* _Nullable)value;
@end

#endif
